---
- name: gems | install base gems
  gem:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    user_install: no
    state: present
  sudo: yes
  with_items:
    - { name: "unicorn", version: "4.8.3" }
    - { name: "dep", version: "1.0.6" }
    - { name: "shotgun", version: "0.9" }
