---
- name: apt cache is up to date
  apt:
    update_cache: yes
  become: yes
  become_method: sudo

- name: project apt dependencies installed
  apt:
    name: "{{ item }}"
  become: yes
  become_method: sudo
  with_items:
    - build-essential
    - git
    - curl
    - libpcre3-dev
    - python-apt
    - python-pycurl
    - python-boto

- name: user owns base directory
  file:
    path: "{{ base_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
  become_method: sudo
