export const DEFAULT_SUBREDDIT = "worldnews";
export const REDDIT_URL = "https://www.reddit.com";
export const SUBREDDIT_URL = "https://www.reddit.com/r/%s.json";
export const OPEN_GRAPH_URL = "https://opengraph.io/api/1.0/site/%s"
export const OPEN_GRAPH_APP_ID = "58928eca4169dc0e00b312fd";
export const POSTS_PER_PAGE = 10;
export const NAME = "WORLDNEWS";
export const TAGLINE = "Popular news curated by Reddit - Made by Form & Function";
export const DESCRIPTION = "Enjoy the most popular news of the day curated by the Reddit Community.";
export const KEYWORDS = "worldnews, news, reddit, popular, politics, economy, client, alternative";
export const AUTHORS = "Sebastian Borrazas, Santiago Alonso",
