---
- name: gems | ensure gem home directory exists
  file:
    path: "{{ app_env.GEM_HOME }}"
    state: directory

- name: gems | add GEM_HOME to PATH
  lineinfile:
    state: present
    line: "export GEM_HOME={{ app_env.GEM_HOME }}"
    dest: "/home/{{ user }}/.bashrc"

- name: gems | install project gems
  shell: dep install
  args:
    chdir: "{{ release_path }}"
  environment: app_env
