---
- set_fact:
    release_version: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- set_fact:
    release_dir: "{{ base_dir }}/current"

- set_fact:
    release_dir: "{{ base_dir }}/releases/{{ release_version }}"
  tags:
    - remote

- include: remote-fetch.yml
  tags:
    - remote

- include: assets.yml
  tags:
    - remote

- name: symlink to app directoy exists
  file:
    state: link
    src: "{{ release_dir }}"
    dest: "{{ app_dir }}"
  tags:
    - remote
