---
- set_fact:
    release_version: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"

- set_fact:
    release_path:
      "{% if app_debug_mode %}{{ app_dir }}{% else %}{{ base_path }}/releases/{{ release_version }}{% endif %}"

- include: remote-fetch.yml
  when: not app_debug_mode

- name: add project settings
  template:
    src: "settings.json.j2"
    dest: "{{ release_path }}/config/settings.json"

- name: add unicorn config file
  template:
    src: "unicorn.rb.j2"
    dest: "{{ release_path }}/config/unicorn.rb"
  when: not app_debug_mode

- include: gems.yml
- include: assets.yml
  when: not app_debug_mode

- include: remote-stop.yml
  when: not app_debug_mode

- include: remote-start.yml
  when: not app_debug_mode
