---
- hosts: all
  remote_user: "{{ root_user }}"
  roles:
    - role: common.remote
      tags:
        -  remote

- hosts: all
  remote_user: "{{ user }}"
  roles:
    - role: common
    - role: webserver
      static: True

- include: deploy.yml
