---
- hosts: staging:production
  remote_user: "{{ root_user }}"
  roles:
    - role: common.remote

- hosts: all
  remote_user: "{{ user }}"
  roles:
    - role: common
    - role: ruby
    - role: webserver

- hosts: all
  remote_user: "{{ user }}"
  sudo_user: "{{ user }}"
  vars:
    base_path: "{{ app_dir | dirname }}"
    repo_version: "master"
    app_env:
      GEM_HOME: "/home/{{ user }}/.gems"
      PATH: "/home/{{ user }}/npm/bin:{{ lookup('env', 'PATH') }}"
  roles:
    - role: deploy
